Reverting 6fa113eaa8e - causes compile error on Linux w/ gcc 13.2.0-23ubuntu4
Was causing the following error:

include/unicode/localpointer.h:561:26: error: ‘auto’ parameter not permitted in this context
  561 | template <typename Type, auto closeFunction>